import { Aside } from "@/components/aside/Aside";
import { Header } from "@/components/header/Header";
import { List } from "@/components/list/List";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header />
      <Aside />
      <main>
        <List />
      </main>
    </>
  );
}
